{% set name = "pyemcee" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyemcee-{{ version }}.tar.gz
  sha256: 6277bb06a133a5ab8f4cff1296ff8698ffebbdc41cce600e44b43ff199879721

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - numpy >=1.15
    - scipy >=1.2
    - matplotlib-base >=2.2
  run:
    - python >={{ python_min }}
    - numpy >=1.15
    - scipy >=1.2
    - matplotlib-base >=2.2

test:
  imports:
    - pyemcee
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mcfit/pyemcee
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: 'pyemcee: Python implementation of the affine-invariant MCMC Hammer'
  dev_url: https://github.com/mcfit/pyemcee
  doc_url: https://pypi.python.org/pypi/pyemcee

extra:
  recipe-maintainers:
    - danehkar
